name: mood_calendar
description: Journal your mood in a fun way

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  localstore: ^1.3.4
  table_calendar: ^3.0.9
  timezone: ^0.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17

  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/play_store_512.png
  color: "#F3B8C1"

flutter:
  uses-material-design: true
